### ISSUE TITLE
trip_list modes - catch-alls?

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/dyno-demand#1]
_transit mode_ = _any_: Alireza's FAST-TrIPs didn't use modes so there was a default transit mode that basically meant any transit mode is ok.  Dan configured demand similarly but used the word "transit" to mean this.  Should we have a special word for any transit mode is ok?

Similar question RE: access and egress modes.  Should we have a stand-in to say any is ok?  This one makes less sense to me, I think walk would be the default.

Maybe this field is always required but "transit" means any transit mode?  So those entries should be "walk-transit-walk"?  (This makes parsing easier...)

**Comment by e-lo** [comment]
@lmz , I think this is a [Fast-Trips](https://github.com/MetropolitanTransportationCommission/fast-trips) issue, not spec?  

I think it just needs to match up with the config file, so if 
`mode = walk-local_bus-walk`
then there should be a path-building config named `walk-local_bus-walk` that specifies something like:
- `access_mode=walk`
- `egress_mode=walk`
- `transit_network_modes`=[`local_bus`, `shuttles`]

...or something like that?  If you have generic transit mode, then that can be a pathbuilding one as well (or you could have a lookup whereby 'transit' is an alias for something else if you want)
[walk-transit-walk]:
- `access_mode=walk`
- `egress_mode=walk`
- `transit_network_modes`=[`local_bus`,`heavy_rail`,`commuter_rail`,`light_rail`,`premium_bus`, `shuttles` etc. ]

**Comment by lmz** [comment]
That's true, it's a fast-trips thing, sorry!  :smile_cat: 
I'll move this to an asana task
