### ISSUE TITLE
Add unique trip list id num?

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/dyno-demand#2]
I'm finding I need a trip list ID num (basically a row num) in the trip_list.txt file because typically I want to dig down at a trip-level, not a person level (since that could include many trips).  This simplifies joining on results, etc.

I'm adding it to output but it seems like it'd be useful to have in the input trip_list.txt file too.

**Comment by e-lo** [comment]
@lmz thinking ahead, it would be good to make this persistent rather than strictly a function of the file order so that it can be safely jumbled around in processing.  Can we do a join of hh, person, and trip id for that person ?  or do you need something more 1:N where N is the size of the file?

**Comment by lmz** [comment]
Good point; I'm happy to use hh, person, and trip id for that person and a string instead of a number -- that would be consistent with our other unique IDs which can be strings.  In which case, maybe unique trip id (which also could be a string) per person suffices?

**Comment by e-lo** [comment]
I like that
