### ISSUE TITLE
Categories in worker_status

### ISSUE THREAD

**Issue by bhargavasana** [osplanning-data-standards/dyno-demand#5]
There are only two categories given: full-time and unemployed. It is not clear what needs to done with part-time employees and student workers. If we want to combine them under 'full-time', maybe the category label needs to change to 'employed' or 'hasajob'?

**Comment by e-lo** [comment]
There are two _suggested_ categories given.  More suggestions can be added - what do you think we should put?

**Comment by bhargavasana** [comment]
Understood. I was looking at OBS_to_DynoDemand script and thought that may be only two categories are needed by FT. After reading the documentation (https://github.com/psrc/FastTrips_PathChoice_Validation/tree/master/OBS_to_DynoDemand), I found that full-  and part-time were not recorded separately in OBS. Sorry for the confusion!
